#### The disadvantage of DT is it get overfit, To resolve this we Use Ensamble Techniques.

#### Ensamble Techniques :

It is a ML Technique which uses multiple algorithms to improve the model performance.

When Decision Tree is not performing well then we use ensambling techniques

Ensamble Techniques

|---> 1. Bagging : It is an ensambling technique which uses 100s of decision tree by default and  paralelly process them all.

         Bagging is used to reduce the variance when Model is Overfit.

|---> 2. Boosting : It is an ensambling technique which uses 100s of decision tree by default and  Sequentially process them all.
 
         Boosting is used to reduce the bias when Model is Underfit

### Random Forest

It is a supervised learning algorithm which comes under bagging ensamble techniques and we can use this for both regression and classification.

Random Forest is used when DT is overfit

When Not to use Random Forest : > When DT is Underfit
                                > For larger dataset

How Random Forest Works :

 Step 1 : Creates 100 decision Trees

 step 2 : Create random Sample for all 100 trees with the help of bootstramping,sampling techniques

 step 3 : Parallely trains all 100 trees, so here tress are "independent"

 step 4 : prediction of output - for Classification : It takes the majority among the 100 output
 
                            for Regression  : It takes the Average of 100 output

### Implementation of Random Forest On  "loan_data.csv" Dataset

In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('loan_data.csv')

In [6]:
df.head(10)

   person_age person_gender  ... previous_loan_defaults_on_file  loan_status
0        22.0        female  ...                             No            1
1        21.0        female  ...                            Yes            0
2        25.0        female  ...                             No            1
3        23.0        female  ...                             No            1
4        24.0          male  ...                             No            1
5        21.0        female  ...                             No            1
6        26.0        female  ...                             No            1
7        24.0        female  ...                             No            1
8        24.0        female  ...                             No            1
9        21.0        female  ...                             No            1

[10 rows x 14 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

In [8]:
X = df.drop("loan_status", axis=1)

y = df["loan_status"]

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
)

In [10]:
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder

In [11]:
from sklearn.compose import ColumnTransformer

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

In [13]:
df

       person_age person_gender  ... previous_loan_defaults_on_file  loan_status
0            22.0        female  ...                             No            1
1            21.0        female  ...                            Yes            0
2            25.0        female  ...                             No            1
3            23.0        female  ...                             No            1
4            24.0          male  ...                             No            1
...           ...           ...  ...                            ...          ...
44995        27.0          male  ...                             No            1
44996        37.0        female  ...                             No            1
44997        33.0          male  ...                             No            1
44998        29.0          male  ...                             No            1
44999        24.0          male  ...                             No            1

[45000 rows x 14 columns]

In [14]:
df['person_education'].unique()

array(['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate'],
      dtype=object)

In [15]:
preprocessing = ColumnTransformer(
    transformers=[
        ('OneHotEncoder', OneHotEncoder(sparse_output=False,handle_unknown='ignore'),['person_gender','person_home_ownership','loan_intent','previous_loan_defaults_on_file']),
        ('OrdinalEncoder',OrdinalEncoder(categories=[['High School','Bachelor','Associate','Master','Doctorate']]),['person_education'])
    ]
)

In [16]:
from sklearn.pipeline import Pipeline

In [17]:
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor

In [20]:
model = RandomForestClassifier(n_estimators=100)

In [21]:
main_pipeline = Pipeline([
    ("preprocessor", preprocessing),
    ("model", RandomForestClassifier(random_state=42))
])

In [22]:
main_pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('OneHotEncoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['person_gender',
                                                   'person_home_ownership',
                                                   'loan_intent',
                                                   'previous_loan_defaults_on_file']),
                                                 ('OrdinalEncoder',
                                                  OrdinalEncoder(categories=[['High '
                                                                              'School',
                                                                              'Bachelor',
                                                                              'Associate',
                                                                              'Master',
                                                                              'Doctorate']]),
                                                  ['person_education'])])),
                ('model', RandomForestClassifier(random_state=42))])

In [23]:
y_train_pred = main_pipeline.predict(X_train)
y_test_pred = main_pipeline.predict(X_test)

In [24]:
from sklearn.metrics import classification_report

In [25]:
print(classification_report(y_train, y_train_pred))

              precision    recall  f1-score   support

           0       0.90      0.88      0.89     28010
           1       0.61      0.64      0.62      7990

    accuracy                           0.83     36000
   macro avg       0.75      0.76      0.76     36000
weighted avg       0.83      0.83      0.83     36000

In [26]:
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.89      0.88      0.88      6990
           1       0.60      0.63      0.61      2010

    accuracy                           0.82      9000
   macro avg       0.74      0.75      0.75      9000
weighted avg       0.83      0.82      0.82      9000